/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
Lista de paquetes:
 */
package ud1_ejer7.gui;

import java.awt.Color;
import ud1_ejer7.logica.Logica;

/**
 *  Ventana del ejercicio.
 * Los radiobuttons avisan a la lógica de qué elemento sera el que debe modificarse
 * Cuando se pulsa uno de los botones de los colores se aplica el color especificado
 * por ese color al tipo de elemento definido en los radiobuttons
 * El botn restablecer vuelve todo a su estado inicial
 * 
 * @author Jose Javier BO
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    // referencia a la logica de negocio
    Logica logica;
    
    /**
     * Creates new form VentanaPrincip0al
     */
    public VentanaPrincipal(Logica logica) {
        initComponents();
        this.logica=logica;
        this.logica.setVentana(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgRadiobuttons = new javax.swing.ButtonGroup();
        panelGeneral = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        btnAzul = new javax.swing.JButton();
        btnRojo = new javax.swing.JButton();
        btnVerde = new javax.swing.JButton();
        btnRosa = new javax.swing.JButton();
        panelListado = new javax.swing.JPanel();
        lbListado = new javax.swing.JLabel();
        rbRejilla = new javax.swing.JRadioButton();
        rbFondo = new javax.swing.JRadioButton();
        rbListado = new javax.swing.JRadioButton();
        btnRestablecer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelBotones.setBackground(new java.awt.Color(0, 0, 0));
        panelBotones.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        btnAzul.setText("Azul");
        btnAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulActionPerformed(evt);
            }
        });
        panelBotones.add(btnAzul);

        btnRojo.setText("Rojo");
        btnRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojoActionPerformed(evt);
            }
        });
        panelBotones.add(btnRojo);

        btnVerde.setText("Verde");
        btnVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerdeActionPerformed(evt);
            }
        });
        panelBotones.add(btnVerde);

        btnRosa.setText("Rosa");
        btnRosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRosaActionPerformed(evt);
            }
        });
        panelBotones.add(btnRosa);

        panelListado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelListado.setLayout(new javax.swing.BoxLayout(panelListado, javax.swing.BoxLayout.Y_AXIS));

        lbListado.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbListado.setText("LISTADO");
        panelListado.add(lbListado);

        bgRadiobuttons.add(rbRejilla);
        rbRejilla.setSelected(true);
        rbRejilla.setText("Rejilla");
        rbRejilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRejillaActionPerformed(evt);
            }
        });
        panelListado.add(rbRejilla);

        bgRadiobuttons.add(rbFondo);
        rbFondo.setText("Fondo");
        rbFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFondoActionPerformed(evt);
            }
        });
        panelListado.add(rbFondo);

        bgRadiobuttons.add(rbListado);
        rbListado.setText("Listado");
        rbListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbListadoActionPerformed(evt);
            }
        });
        panelListado.add(rbListado);

        btnRestablecer.setText("Restablecer");
        btnRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRestablecer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento click btnAzul
     * @param evt 
     */
    private void btnAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulActionPerformed
        this.logica.setColor(Color.BLUE);
    }//GEN-LAST:event_btnAzulActionPerformed

    /**
     * Evento click btRojo
     * @param evt 
     */
    private void btnRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojoActionPerformed
        this.logica.setColor(Color.RED);
    }//GEN-LAST:event_btnRojoActionPerformed

    /**
     * Evento click btnVerde
     * @param evt 
     */
    private void btnVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerdeActionPerformed
        this.logica.setColor(Color.GREEN);
    }//GEN-LAST:event_btnVerdeActionPerformed

    /**
     * Evento click btnRosa
     * @param evt 
     */
    private void btnRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRosaActionPerformed
        this.logica.setColor(Color.PINK);
    }//GEN-LAST:event_btnRosaActionPerformed

    /**
     * Evento click radio button rejilla
     * @param evt 
     */
    private void rbRejillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRejillaActionPerformed
       logica.setElemento(Logica.REJILLA);
    }//GEN-LAST:event_rbRejillaActionPerformed

        /**
     * Evento click radio button fondo
     * @param evt 
     */
    private void rbFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFondoActionPerformed
       logica.setElemento(Logica.FONDO);
    }//GEN-LAST:event_rbFondoActionPerformed

        /**
     * Evento click radio button listado
     * @param evt 
     */
    private void rbListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbListadoActionPerformed
       logica.setElemento(Logica.LISTADO);
    }//GEN-LAST:event_rbListadoActionPerformed

        /**
     * Evento click btnRestablecer
     * @param evt 
     */
    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
        this.logica.restablecer();
    }//GEN-LAST:event_btnRestablecerActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgRadiobuttons;
    private javax.swing.JButton btnAzul;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JButton btnRojo;
    private javax.swing.JButton btnRosa;
    private javax.swing.JButton btnVerde;
    private javax.swing.JLabel lbListado;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelListado;
    private javax.swing.JRadioButton rbFondo;
    private javax.swing.JRadioButton rbListado;
    private javax.swing.JRadioButton rbRejilla;
    // End of variables declaration//GEN-END:variables

    public void setColorRejilla(Color color) {
        this.panelBotones.setBackground(color);
    }

    public void setColorFondo(Color color) {
        this.panelGeneral.setBackground(color);
    }

    public void setColorListado(Color color) {
        this.panelListado.setBackground(color);
    }
}
